#!/bin/bash

# Atualiza o gerenciador de pacotes
sudo apt-get update

# Instala o Apache
sudo apt-get install apache2 -y

# Altera a porta de uso do Apache para 8888
sudo sed -i 's/Listen 80/Listen 8888/g' /etc/apache2/ports.conf

# Reinicia o Apache para aplicar a alteração da porta
sudo service apache2 restart

ls /etc/scripts
mkdir -p /etc/scripts
rm /etc/scripts/privonlines.sh
touch /etc/scripts/privonlines.sh
file_path="/etc/scripts/privonlines.sh"

# Define o conteúdo do arquivo
file_content="#!/bin/bash
duplicate_processes=\$(ps -eo command | awk '/^sshd:.*\[priv\]$/ {print \$2}' | sort | uniq -d | grep -vE \"^unknown$|^root$\")
# Verifica se há duplicatas antes de executar o pkill
if [ -n \"\$duplicate_processes\" ]; then
    # Percorre cada duplicata e mata o processo com o comando pkill
    for user in \$duplicate_processes; do
        pkill -f \"\$user\"
    done
fi
# Comando de 10 segundos de descanso, para os duplicados poderem ser reconectados.
sleep 10
# Filtra todos os (sshd: usuario [priv]) do htop novamente
onlines_test=\$(ps -eo command | awk '/^sshd:.*\[priv\]$/ {print \$2}' | sort | grep -vE \"^unknown$|^root$\")
# Copia as informações e salva em um arquivo onlines.txt, caso o arquivo ja exista ele substitui.
echo \"\$onlines_test\" > /var/www/html/onlines.txt
"

# Cria o arquivo e escreve o conteúdo nele
echo "$file_content" > "$file_path"

# Concede a permissão 777 ao arquivo
chmod 777 "$file_path"

#Crie um crontab, de 1 minuto
(crontab -l 2>/dev/null | grep -v '/etc/scripts/privonlines.sh'; echo "* * * * * /etc/scripts/privonlines.sh") | crontab -
