#!/bin/bash
apt-get install kexec-tools
cd /etc
wget https://raw.githubusercontent.com/UltraSSH/script/main/scriptrebootfast
mv /etc/scriptrebootfast /etc/scriptreboot
sudo chmod 777 /etc/scriptreboot
echo -e 
(crontab -l 2>/dev/null; echo "0 */2 * * * root kexec -l /boot/vmlinuz-$(uname -r) --initrd=/boot/initrd.img-$(uname -r) --reuse-cmdline; sleep 10; kexec -e") | crontab -
