#!/bin/bash
apt-get install kexec-tools
mkdir /etc
cd /etc
wget https://raw.githubusercontent.com/UltraSSH/script/main/scriptrebootfast
mv /etc/scriptrebootfast /etc/scriptreboot
sudo chmod 777 /etc/scriptreboot
(crontab -l 2>/dev/null; echo "0 */2 * * * /etc/scriptreboot") | crontab -
