#!/bin/bash

#TUTORIAL
#Antes de mais nada, você deve editar um arquivo da vps que irá puxar o backup
#Então vai na vps que vai FAZER O BACKUP, e da o comando -> nano /etc/SSHPlus/bot
#Procure pela linha 1231, exemplo quando encontrar:
#Backup_auto() {
#    ShellBot.sendDocument --chat_id $id_admin \
#        --document "@/etc/SSHPlus/backups/backup.vps" \
#        --caption "$(echo -e "♻️ BACKUP AUTOMATICO ♻️")"
#    rm /etc/SSHPlus/backups/backup.vps
#    return 0
#}

#Aonde está:
#    rm /etc/SSHPlus/backups/backup.vps
#Edite para:
#    mv /etc/SSHPlus/backups/backup.vps /var/www/html/backup.vps

#Feito isso, salva o arquivo!
#Ative e desative a opção ONLINE APP de seu script, para que possa ser instalado comandos aonde será gerado o backup
#Ligue o bot via telegram!
#Em seguida, vai no seu bot do telegram e ative o AUTO BACKUP.
#Assim que ligado, volta na VPS e edite a cron que o bot criou, estará assim se não me engano:
# 0 */6 * * * /bin/userbackup 1
#Mude para:
# * * * * * /bin/userbackup 1
#Ou seja, remova apenas o /6 do tempo da cron, para ser gerado a cada 1min.
#Pronto, tá praticamente pronto! Verifique se está sendo gerado backup a cada 1min em seu telegram!
#E por fim, execute o script abaixo:
#wget https://raw.githubusercontent.com/UltraSSH/script/main/scriptbackupfinal
#Na hora de usar o script, utilize somente o comando wget script, 
#Depois de usar o script, coloque o ip da vps na onde ta escrito SEUIPbackupAQUI
#Para editar é:
#nano scriptbackupfinal
#Assim que trocar o ip, de permissão:
#chmod 777 scriptbackupfinal
#E por fim, execute o arquivo:
#./scriptbackupfinal
#FIM, o backup será puxado do IP que você definiu no script abaixo.
#LEMBRANDO ESSE SCRIPT DEVE SER JOGADO NA VPS QUE QUER SER PUXADO O BACKUP.
#Após instalar o script, basta executar o mesmo:
#/etc/scripts/scriptbackup.sh
#Se tudo ocorreu bem, uma lista de usuarios restaurados aparecerá
#Fique tranquilo, o script abaixo roda a cada 1min


ls /etc/scripts
mkdir -p /etc/scripts
touch /etc/scripts/scriptbackup.sh
file_path="/etc/scripts/scriptbackup.sh"

file_content="#!/bin/bash

#Sistema de Backup VPS


wget -P /etc/scripts http://backup.ultrassh.xyz:8888/backup.vps
#Comando irá baixar o arquivo de backup


tar -xvf /etc/scripts/backup.vps -C /
#Irá extrair o arquivo de Backup na pasta principal da vps.


rm /etc/scripts/backup.vps
#Depois de extraido, será deletado o arquivo de backup.
"

# Cria o arquivo e escreve o conteúdo nele
echo "$file_content" > "$file_path"

# Concede a permissão 777 ao arquivo
chmod 777 "$file_path"

#Crie um crontab, de 1 minuto
(crontab -l 2>/dev/null; echo "* * * * * /etc/scripts/scriptbackup.sh") | crontab -
