#!/bin/bash

#TUTORIAL
# Primeiro, jogue esse script abaixo na VPS que ira GERAR BACKUP:
#mkdir /etc/scripts && cd /etc/scripts && wget -P /etc/scripts https://raw.githubusercontent.com/UltraSSH/scriptbackup/main/scriptbackup && chmod 777 scriptbackup && /etc/scripts/scriptbackup
# Feito isso, crie um crontab -e para executar o arquivo a cada 1 minuto (ou de acordo com o desejado:
#* * * * * /etc/scripts/scriptbackup


# Pronto, tá praticamente pronto! Verifique se está sendo gerado backup
#cd /var/www/html/
#ls
# Estando tudo certo, prossiga para as maquinas que vão receber o BACKUP...
#Execute o script abaixo nelas
#LEMBRANDO ESSE SCRIPT DEVE SER JOGADO NA VPS QUE QUER SER PUXADO O BACKUP.
#wget https://raw.githubusercontent.com/UltraSSH/script/main/scriptbackupfinal
#Na hora de usar o script, utilize somente o comando wget script, 
#Depois de usar o script, coloque o ip da vps na onde ta escrito SEUIPbackupAQUI
#Para editar é:
#nano scriptbackupfinal
#Assim que trocar o ip, de permissão:
#chmod 777 scriptbackupfinal
#E por fim, execute o arquivo:
#./scriptbackupfinal
#FIM, o backup será puxado do IP que você definiu no script abaixo.
#LEMBRANDO ESSE SCRIPT DEVE SER JOGADO NA VPS QUE QUER SER PUXADO O BACKUP.
#Após instalar o script, basta executar o mesmo:
#/etc/scripts/scriptbackup.sh
#Se tudo ocorreu bem, uma lista de usuarios restaurados aparecerá
#Fique tranquilo, o script abaixo roda a cada 1min


ls /etc/scripts
mkdir -p /etc/scripts
touch /etc/scripts/scriptbackup.sh
file_path="/etc/scripts/scriptbackup.sh"

file_content="#!/bin/bash

#Sistema de Backup VPS


wget -P /etc/scripts http://backup.ultrassh.xyz/backup.vps
#Comando irá baixar o arquivo de backup


tar -xvf /etc/scripts/backup.vps -C /
#Irá extrair o arquivo de Backup na pasta principal da vps.


rm /etc/scripts/backup.vps
#Depois de extraido, será deletado o arquivo de backup.
"

# Cria o arquivo e escreve o conteúdo nele
echo "$file_content" > "$file_path"

# Concede a permissão 777 ao arquivo
chmod 777 "$file_path"

#Crie um crontab, de 1 minuto
(crontab -l 2>/dev/null; echo "* * * * * /etc/scripts/scriptbackup.sh") | crontab -
